# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1


jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: setup
      - run: build 


  test:
    docker:
      - image: circleci/node:13.8.0
    
    steps:
      - checkout
      - run: test



workflows:
  my-workflow: 
    jobs:
      - build
      - test:
        requires:
          - build
      - analyse:
        requires:
          -test
