# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.7


jobs:
  build:
    dockers:
      - circleci/node:13.8.0
    steps:
      - checkout
      - run: setup
      - run: build 


  test:
    dockers:
      - circleci/node:13.8.0
    
    steps:
      - checkout
      - run: test

  analyse:
    dockers:
      - circleci/node:13.8.0
    steps:
      - checkout
      - run: npm audit


workflows:
  my-workflow: 
    jobs:
      - build
      - test:
        requires
          - build
      - analyse:
        requires:
          -test
